import { SEVERITY_WEIGHT } from './checks.js';

const CATEGORY_LABEL = { legal: 'Legal', docs: 'Documentation', community: 'Community', security: 'Security', quality: 'Quality' };
const CATEGORY_ORDER = ['legal', 'docs', 'community', 'security', 'quality'];

function byCategory(results) {
  return CATEGORY_ORDER.map((c) => [c, results.filter((r) => r.category === c)]).filter(([, rs]) => rs.length);
}

function potentialGain(report, r) {
  const total = report.results.filter((x) => x.status !== 'skip').reduce((s, x) => s + SEVERITY_WEIGHT[x.severity], 0);
  return total ? Math.round((SEVERITY_WEIGHT[r.severity] / total) * 100) : 0;
}

export function text(report, { color = true, verbose = false } = {}) {
  const c = (code) => (s) => (color ? `\x1b[${code}m${s}\x1b[0m` : s);
  const green = c('32'); const red = c('31'); const yellow = c('33'); const dim = c('2'); const bold = c('1'); const cyan = c('36');
  const icon = (r) => {
    if (r.status === 'pass') return green('✔');
    if (r.status === 'skip') return dim('–');
    return r.severity === 'error' ? red('✖') : r.severity === 'warning' ? yellow('▲') : cyan('○');
  };
  const scoreColor = report.score >= 90 ? green : report.score >= 65 ? yellow : red;

  const out = [];
  out.push('');
  out.push(`${bold('repo-ready')} ${dim(report.root)}`);
  for (const [cat, rs] of byCategory(report.results)) {
    out.push('');
    out.push(bold(CATEGORY_LABEL[cat]));
    for (const r of rs) {
      if (r.status === 'skip' && !verbose) continue;
      out.push(`  ${icon(r)} ${r.title} ${dim('—')} ${r.status === 'pass' || r.status === 'skip' ? dim(r.message) : r.message}`);
      if (r.status === 'fail') {
        for (const d of r.details || []) out.push(`      ${dim(d)}`);
        if (verbose) out.push(`      ${dim(r.description)}`);
      }
    }
  }

  if (report.fixed.length) {
    out.push('');
    out.push(bold('Created'));
    for (const f of report.fixed) out.push(`  ${green('+')} ${f.file}`);
  }

  const failing = report.results.filter((r) => r.status === 'fail');
  out.push('');
  out.push(`${bold('Score:')} ${scoreColor(bold(`${report.score}/100`))} ${scoreColor(`(${report.grade})`)}  ${dim(`${report.counts.pass} passed, ${report.counts.fail} failed, ${report.counts.skip} skipped`)}`);
  const fixable = failing.filter((r) => r.fixable);
  if (fixable.length && !report.fixed.length) {
    out.push(`Run ${bold('repo-ready --fix')} to auto-fix ${fixable.length} of these.`);
  }
  if (report.minScore != null && report.score < report.minScore) {
    out.push(red(`Score is below the minimum of ${report.minScore}.`));
  }
  out.push('');
  return out.join('\n');
}

export function json(report) {
  return `${JSON.stringify(report, null, 2)}\n`;
}

export function markdown(report) {
  const emoji = (r) => {
    if (r.status === 'pass') return '✅';
    if (r.status === 'skip') return '➖';
    return r.severity === 'error' ? '❌' : r.severity === 'warning' ? '⚠️' : 'ℹ️';
  };
  const esc = (s) => String(s).replace(/\|/g, '\\|').replace(/\n/g, ' ');
  const lines = [];
  lines.push(`## repo-ready: ${report.score}/100 (${report.grade})`);
  lines.push('');
  lines.push(`**${report.counts.pass}** passed · **${report.counts.fail}** failed · **${report.counts.skip}** skipped`);
  lines.push('');
  lines.push('| | Check | Result |');
  lines.push('|---|---|---|');
  for (const [, rs] of byCategory(report.results)) {
    for (const r of rs) {
      if (r.status === 'skip') continue;
      const detail = r.status === 'fail' && r.details?.length ? `<br><sub>${r.details.slice(0, 5).map(esc).join('<br>')}</sub>` : '';
      lines.push(`| ${emoji(r)} | ${esc(r.title)} | ${esc(r.message)}${detail} |`);
    }
  }
  const failing = report.results.filter((r) => r.status === 'fail').sort((a, b) => SEVERITY_WEIGHT[b.severity] - SEVERITY_WEIGHT[a.severity]);
  if (failing.length) {
    lines.push('');
    lines.push('### Top improvements');
    lines.push('');
    for (const r of failing.slice(0, 5)) {
      lines.push(`- **${r.title}** (+${potentialGain(report, r)} pts): ${r.description}${r.fixable ? ' _Auto-fixable with `npx repo-ready --fix`._' : ''}`);
    }
  }
  lines.push('');
  lines.push('<sub>Generated by [repo-ready](https://github.com/macodev00/Idk-letting-opus-decide)</sub>');
  return `${lines.join('\n')}\n`;
}

export function sarif(report, { version = '1.0.0' } = {}) {
  const failing = report.results.filter((r) => r.status === 'fail');
  const level = { error: 'error', warning: 'warning', info: 'note' };
  const results = [];
  for (const r of failing) {
    const locations = [];
    for (const d of r.details || []) {
      const m = String(d).match(/^([^\s:]+):(\d+)\b/);
      if (m) locations.push({ physicalLocation: { artifactLocation: { uri: m[1] }, region: { startLine: Number(m[2]) } } });
    }
    if (!locations.length) locations.push({ physicalLocation: { artifactLocation: { uri: 'README.md' }, region: { startLine: 1 } } });
    for (const location of locations) {
      results.push({ ruleId: r.id, level: level[r.severity], message: { text: `${r.title}: ${r.message}` }, locations: [location] });
    }
  }
  const doc = {
    $schema: 'https://json.schemastore.org/sarif-2.1.0.json',
    version: '2.1.0',
    runs: [{
      tool: {
        driver: {
          name: 'repo-ready',
          version,
          informationUri: 'https://github.com/macodev00/Idk-letting-opus-decide',
          rules: report.results.map((r) => ({
            id: r.id,
            name: r.title,
            shortDescription: { text: r.title },
            fullDescription: { text: r.description },
            defaultConfiguration: { level: level[r.severity] },
          })),
        },
      },
      results,
    }],
  };
  return `${JSON.stringify(doc, null, 2)}\n`;
}

export function badge(report) {
  const colorFor = report.score >= 90 ? 'brightgreen' : report.score >= 80 ? 'green' : report.score >= 65 ? 'yellow' : report.score >= 50 ? 'orange' : 'red';
  return `https://img.shields.io/badge/repo--ready-${report.score}%2F100-${colorFor}`;
}
